--CREATING TABLES
-- Drop old tables if they exist (optional)
-- DROP TABLE Billing;
-- DROP TABLE Medical_Records;
-- DROP TABLE Appointments;
-- DROP TABLE Insurance;
-- DROP TABLE Doctors;
-- DROP TABLE Patients;

-- Patients
CREATE TABLE Patients (
  Patient_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  First_Name   VARCHAR2(50) NOT NULL,
  Last_Name    VARCHAR2(50) NOT NULL,
  DOB          DATE NOT NULL,
  Gender       VARCHAR2(10),
  Contact_No   VARCHAR2(20),
  Address      VARCHAR2(200)
);

-- Doctors
CREATE TABLE Doctors (
  Doctor_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  First_Name   VARCHAR2(50) NOT NULL,
  Last_Name    VARCHAR2(50) NOT NULL,
  Specialization VARCHAR2(50),
  Contact_No   VARCHAR2(20)
);

-- Appointments
CREATE TABLE Appointments (
  Appt_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Patient_ID   NUMBER NOT NULL,
  Doctor_ID    NUMBER NOT NULL,
  Appt_Date    DATE NOT NULL,
  Status       VARCHAR2(20) DEFAULT 'Scheduled',
  CONSTRAINT fk_appt_patient FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID),
  CONSTRAINT fk_appt_doctor  FOREIGN KEY (Doctor_ID)  REFERENCES Doctors(Doctor_ID)
);

-- Medical Records
CREATE TABLE Medical_Records (
  Record_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Patient_ID   NUMBER NOT NULL,
  Doctor_ID    NUMBER NOT NULL,
  Diagnosis    VARCHAR2(200),
  Prescription VARCHAR2(200),
  Record_Date  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_medrec_patient FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID),
  CONSTRAINT fk_medrec_doctor  FOREIGN KEY (Doctor_ID)  REFERENCES Doctors(Doctor_ID)
);

-- Billing
CREATE TABLE Billing (
  Bill_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Appt_ID       NUMBER UNIQUE, -- one bill per appointment
  Patient_ID    NUMBER NOT NULL,
  Amount        NUMBER(10,2) DEFAULT 0,
  Payment_Status VARCHAR2(20) DEFAULT 'Pending',
  Bill_Date     DATE,
  CONSTRAINT fk_billing_appt FOREIGN KEY (Appt_ID) REFERENCES Appointments(Appt_ID),
  CONSTRAINT fk_billing_patient FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID)
);

-- Insurance
CREATE TABLE Insurance (
  Insurance_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Patient_ID     NUMBER NOT NULL,
  Provider_Name  VARCHAR2(100),
  Policy_No      VARCHAR2(50) UNIQUE,
  Coverage_Amount NUMBER,
  Expiry_Date    DATE,
  CONSTRAINT fk_ins_patient FOREIGN KEY (Patient_ID) REFERENCES Patients(Patient_ID)
);

-- Ops log (for logging if needed later)
CREATE TABLE ops_log (
  log_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
  module     VARCHAR2(50),
  action     VARCHAR2(100),
  details    VARCHAR2(4000),
  err_code   NUMBER,
  err_msg    VARCHAR2(4000)
);
