-- DEPARTMENTS TABLE
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO DEPARTMENTS VALUES (1, 'Cardiology');
INSERT INTO DEPARTMENTS VALUES (2, 'Neurology');
INSERT INTO DEPARTMENTS VALUES (3, 'Orthopedics');

-- DOCTORS TABLE UPDATE
ALTER TABLE DOCTORS ADD DEPARTMENT_ID NUMBER;

ALTER TABLE DOCTORS
ADD CONSTRAINT FK_DOCTOR_DEPT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID);

-- BILLING FIX
ALTER TABLE BILLING DROP COLUMN PATIENT_ID;

-- APPOINTMENT STATUS
ALTER TABLE APPOINTMENTS ADD STATUS VARCHAR2(50);

-- STATUS HISTORY TABLE
CREATE TABLE APPOINTMENT_STATUS_HISTORY (
    STATUS_ID NUMBER PRIMARY KEY,
    APPOINTMENT_ID NUMBER,
    STATUS VARCHAR2(50),
    STATUS_DATE DATE,
    UPDATED_BY VARCHAR2(50),
    CONSTRAINT FK_STATUS_APPT
    FOREIGN KEY (APPOINTMENT_ID)
    REFERENCES APPOINTMENTS(APPOINTMENT_ID)
);

-- SEQUENCE
CREATE SEQUENCE STATUS_SEQ START WITH 1 INCREMENT BY 1;
