CREATE OR REPLACE PACKAGE HEALTHCARE_PKG AS

    PROCEDURE UPDATE_APPOINTMENT_STATUS (
        P_APPOINTMENT_ID NUMBER,
        P_STATUS VARCHAR2
    );

    FUNCTION GET_PATIENT_FROM_BILLING (
        P_BILL_ID NUMBER
    ) RETURN NUMBER;

END HEALTHCARE_PKG;
/

CREATE OR REPLACE PACKAGE BODY HEALTHCARE_PKG AS

    PROCEDURE UPDATE_APPOINTMENT_STATUS (
        P_APPOINTMENT_ID NUMBER,
        P_STATUS VARCHAR2
    ) IS
    BEGIN
        -- Validate status
        IF P_STATUS NOT IN ('SCHEDULED','CONFIRMED','COMPLETED','CANCELLED') THEN
            RAISE_APPLICATION_ERROR(-20002, 'Invalid Status Value');
        END IF;

        -- Update status
        UPDATE APPOINTMENTS
        SET STATUS = P_STATUS
        WHERE APPOINTMENT_ID = P_APPOINTMENT_ID;

        -- Check if appointment exists
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Invalid Appointment ID');
        END IF;

    END UPDATE_APPOINTMENT_STATUS;


    FUNCTION GET_PATIENT_FROM_BILLING (
        P_BILL_ID NUMBER
    ) RETURN NUMBER IS
        V_PATIENT_ID NUMBER;
    BEGIN
        SELECT A.PATIENT_ID
        INTO V_PATIENT_ID
        FROM BILLING B
        JOIN APPOINTMENTS A
        ON B.APPOINTMENT_ID = A.APPOINTMENT_ID
        WHERE B.BILL_ID = P_BILL_ID;

        RETURN V_PATIENT_ID;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_PATIENT_FROM_BILLING;

END HEALTHCARE_PKG;
/
