CREATE OR REPLACE TRIGGER TRG_APPOINTMENT_STATUS
AFTER UPDATE OF STATUS ON APPOINTMENTS
FOR EACH ROW
BEGIN
    INSERT INTO APPOINTMENT_STATUS_HISTORY (
        STATUS_ID,
        APPOINTMENT_ID,
        STATUS,
        STATUS_DATE,
        UPDATED_BY
    )
    VALUES (
        STATUS_SEQ.NEXTVAL,
        :NEW.APPOINTMENT_ID,
        :NEW.STATUS,
        SYSDATE,
        USER
    );
END;
/
