BEGIN
    HEALTHCARE_PKG.UPDATE_APPOINTMENT_STATUS(101, 'CONFIRMED');
END;
/

SELECT * FROM APPOINTMENT_STATUS_HISTORY;

SELECT HEALTHCARE_PKG.GET_PATIENT_FROM_BILLING(401) FROM DUAL;

SELECT * FROM BILLING_DETAILS;
